theme: jekyll-theme-minimal
title: Johannah O'Mahony
description: PhD Student at the University of Edinburgh School of Informatics
logo: <img src="https://user-images.githubusercontent.com/18417271/130977569-70ee9bfd-5f8d-4e81-9f97-4a87b111876e.jpg" width="187" height="250">

